export const TEAMS_LOAD = 'TEAMS_LOAD';
export const TEAMS_LOAD_SUCCESS = 'TEAMS_LOAD_SUCCESS';
export const TEAMS_LOAD_FAIL = 'TEAMS_LOAD_FAIL';

export const TEAM_CREATE = 'TEAM_CREATE';
export const TEAM_CREATE_SUCCESS = 'TEAM_CREATE_SUCCESS';
export const TEAM_CREATE_FAIL = 'TEAM_CREATE_FAIL';

export const TEAM_UPDATE = 'TEAM_UPDATE';
export const TEAM_UPDATE_SUCCESS = 'TEAM_UPDATE_SUCCESS';
export const TEAM_UPDATE_FAIL = 'TEAM_UPDATE_FAIL';

export const TEAM_DELETE = 'TEAM_DELETE';
export const TEAM_DELETE_SUCCESS = 'TEAM_DELETE_SUCCESS';
export const TEAM_DELETE_FAIL = 'TEAM_DELETE_FAIL';

export const TEAM_DELETE_COLLECTION = 'TEAM_DELETE_COLLECTION';
export const TEAM_DELETE_COLLECTION_SUCCESS = 'TEAM_DELETE_COLLECTION_SUCCESS';
export const TEAM_DELETE_COLLECTION_FAIL = 'TEAM_DELETE_COLLECTION_FAIL';



export const SURVEY_LOAD = 'SURVEY_LOAD';
export const SURVEY_LOAD_SUCCESS = 'SURVEY_LOAD_SUCCESS';
export const SURVEY_LOAD_FAIL = 'SURVEY_LOAD_FAIL';

export const SURVEY_CREATE = 'SURVEY_CREATE';
export const SURVEY_CREATE_SUCCESS = 'SURVEY_CREATE_SUCCESS';
export const SURVEY_CREATE_FAIL = 'SURVEY_CREATE_FAIL';